### ISSUE TITLE
MSVCR110.dll missing

### ISSUE THREAD

**Issue by alain01** [Bearsampp/prerequisites#12]
#### Steps to reproduce this issue

1. Ms Windows11 24H2
2. Install Bearsampp-prerequisites-2024.4.20.exe
3. Launch bearsampp (Bearsampp-basic-2024.8.20)
4. See Error at the the launcher

MSVCR110.dll missing

=================

Install [https://www.microsoft.com/en-us/download/details.aspx?id=30679](https://www.microsoft.com/en-us/download/details.aspx?id=30679)
Visual C++ Redistributable for Visual Studio 2012 Update 4

Then it's ok with 3 restarts bearsamp

Alain

**Comment by N6REJ** [comment]
what version of windows were you installing it on?

**Comment by N6REJ** [comment]
That shouldn't be necessary anymore.  We don't support the old os's.  Windows 10+ now.
Supported Operating Systems for vs 2012

Windows 7 Service Pack 1, Windows 8, Windows 8.1, Windows Server 2003, Windows Server 2008 R2 SP1, Windows Server 2008 Service Pack 2, Windows Server 2012, Windows Vista Service Pack 2, Windows XP

**Comment by alain01** [comment]
???
My OS is Windows 11 24H2 and I Got this message !

**Comment by N6REJ** [comment]
not sure why its being requested ( we're looking into it ) but this pr address's the issue https://github.com/Bearsampp/prerequisites/pull/13
