### ISSUE TITLE
Official URL for prerequisite

### ISSUE THREAD

**Issue by alain01** [Bearsampp/prerequisites#2]
I think it' s better to link to the official URL.
You exe file is considered as a suspiscious file for my system.

Why not give the link to the original source?

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by N6REJ** [comment]
thats not JUST vsc that was updated.  There's a bit more but it shouldn't be throwing a error like that.  What was the exact error?  Do you get the same error when using neard's prerequisite file?

**Comment by alain01** [comment]
Ok I close this issue cause yes, it's not just 1 file.
After I used  the prerequisite bearsampp-prerequisites .
See https://github.com/Bearsampp/Bearsampp/issues/27
